// ui/poc-react/src/components/ConnectorsTable.tsx
/**
 * Connectors Table Component
 *
 * Displays a table of Kafka connectors with filtering and pagination
 */

import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Toolbar,
  ToolbarContent,
  ToolbarItem,
  SearchInput,
  EmptyState,
  EmptyStateBody,
  Spinner,
  Pagination,
} from '@patternfly/react-core';
import {
  Table,
  Thead,
  Tr,
  Th,
  Tbody,
  Td,
  ThProps,
} from '@patternfly/react-table';
import {
  CheckCircleIcon,
  ExclamationCircleIcon,
  PauseCircleIcon,
  PendingIcon,
  HistoryIcon,
} from '@patternfly/react-icons';
import { useTranslation } from 'react-i18next';
import { useConnectors } from '../api/hooks/useConnect';
import { ConnectorState, ConnectorType, EnrichedConnector } from '../api/types';
import { ManagedConnectorLabel } from './ManagedConnectorLabel';
import stopIcon from '/stop-icon.svg';

interface ConnectorsTableProps {
  kafkaId: string | undefined;
}

const StateIcon: Record<ConnectorState, React.ReactNode> = {
  UNASSIGNED: <PendingIcon />,
  RUNNING: <CheckCircleIcon color="var(--pf-t--global--icon--color--status--success--default)" />,
  PAUSED: <PauseCircleIcon />,
  STOPPED: <img src={stopIcon} alt="stopped" style={{ width: '1em', height: '1em' }} />,
  FAILED: <ExclamationCircleIcon color="var(--pf-t--global--icon--color--status--danger--default)" />,
  RESTARTING: <HistoryIcon />,
};

const StateLabel: Record<ConnectorState, string> = {
  UNASSIGNED: 'Unassigned',
  RUNNING: 'Running',
  PAUSED: 'Paused',
  STOPPED: 'Stopped',
  FAILED: 'Failed',
  RESTARTING: 'Restarting',
};

const TypeLabel: Record<ConnectorType, string> = {
  source: 'Source',
  sink: 'Sink',
  'source:mm': 'Mirror Source',
  'source:mm-checkpoint': 'Mirror Checkpoint',
  'source:mm-heartbeat': 'Mirror Heartbeat',
};

export function ConnectorsTable({ kafkaId }: ConnectorsTableProps) {
  const { t } = useTranslation();
  const [searchValue, setSearchValue] = useState('');
  const [sortBy, setSortBy] = useState<string>('name');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
  const [page, setPage] = useState(1);
  const [perPage, setPerPage] = useState(20);

  const { data, isLoading, error } = useConnectors(kafkaId, {
    pageSize: perPage,
    name: searchValue || undefined,
    sort: sortBy,
    sortDir: sortDirection,
  });

  const connectors = data?.data || [];
  const totalItems = data?.meta?.page?.total || 0;

  const handlePageChange = (newPage: number, newPerPage: number) => {
    setPage(newPage);
    setPerPage(newPerPage);
  };

  const handleSort = (columnKey: string) => {
    if (sortBy === columnKey) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(columnKey);
      setSortDirection('asc');
    }
  };

  const getSortParams = (columnKey: string): ThProps['sort'] => ({
    sortBy: {
      index: sortBy === columnKey ? 0 : undefined,
      direction: sortDirection,
    },
    onSort: () => handleSort(columnKey),
    columnIndex: 0,
  });

  if (error) {
    return (
      <EmptyState>
        <ExclamationCircleIcon />
        <h4>Error loading connectors</h4>
        <EmptyStateBody>{error.message}</EmptyStateBody>
      </EmptyState>
    );
  }

  return (
    <>
      <Toolbar>
        <ToolbarContent>
          <ToolbarItem>
            <SearchInput
              placeholder={t('kafka.connect.searchConnectors', 'Search connectors')}
              value={searchValue}
              onChange={(_event, value) => setSearchValue(value)}
              onClear={() => setSearchValue('')}
            />
          </ToolbarItem>
          <ToolbarItem variant="pagination" align={{ default: 'alignEnd' }}>
            <Pagination
              itemCount={totalItems}
              page={page}
              perPage={perPage}
              onSetPage={(_, newPage) => handlePageChange(newPage, perPage)}
              onPerPageSelect={(_, newPerPage) => handlePageChange(1, newPerPage)}
              variant="top"
              isCompact
            />
          </ToolbarItem>
        </ToolbarContent>
      </Toolbar>

      {isLoading ? (
        <EmptyState>
          <Spinner />
          <h4>Loading connectors</h4>
        </EmptyState>
      ) : connectors.length === 0 ? (
        <EmptyState>
          <h4>{t('kafka.connect.noConnectors', 'No connectors found')}</h4>
          <EmptyStateBody>
            {searchValue
              ? t('kafka.connect.noConnectorsMatch', 'No connectors match your search criteria')
              : t('kafka.connect.noConnectorsAvailable', 'No connectors are available')}
          </EmptyStateBody>
        </EmptyState>
      ) : (
        <Table aria-label="Connectors table" variant="compact">
          <Thead>
            <Tr>
              <Th {...getSortParams('name')}>{t('kafka.connect.name', 'Name')}</Th>
              <Th {...getSortParams('connect-cluster')}>
                {t('kafka.connect.connectCluster', 'Connect cluster')}
              </Th>
              <Th>{t('kafka.connect.type', 'Type')}</Th>
              <Th>{t('kafka.connect.state', 'State')}</Th>
              <Th>{t('kafka.connect.tasks', 'Tasks')}</Th>
            </Tr>
          </Thead>
          <Tbody>
            {connectors.map((connector) => (
              <Tr key={connector.id}>
                <Td dataLabel={t('kafka.connect.name', 'Name')}>
                  <Link to={`/kafka/${kafkaId}/connect/connectors/${encodeURIComponent(connector.id)}`}>
                    {connector.attributes.name}
                  </Link>
                  {connector.meta?.managed === true && <ManagedConnectorLabel />}
                </Td>
                <Td dataLabel={t('kafka.connect.connectCluster', 'Connect cluster')}>
                  {connector.connectClusterId ? (
                    <Link
                      to={`/kafka/${kafkaId}/connect/clusters/${connector.connectClusterId}`}
                    >
                      {connector.connectClusterName}
                    </Link>
                  ) : (
                    '-'
                  )}
                </Td>
                <Td dataLabel={t('kafka.connect.type', 'Type')}>
                  {TypeLabel[connector.attributes.type]}
                </Td>
                <Td dataLabel={t('kafka.connect.state', 'State')}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    {StateIcon[connector.attributes.state]}
                    {StateLabel[connector.attributes.state]}
                  </span>
                </Td>
                <Td dataLabel={t('kafka.connect.tasks', 'Tasks')}>{connector.replicas ?? '-'}</Td>
              </Tr>
            ))}
          </Tbody>
        </Table>
      )}

      <Toolbar>
        <ToolbarContent>
          <ToolbarItem variant="pagination" align={{ default: 'alignEnd' }}>
            <Pagination
              itemCount={totalItems}
              page={page}
              perPage={perPage}
              onSetPage={(_, newPage) => handlePageChange(newPage, perPage)}
              onPerPageSelect={(_, newPerPage) => handlePageChange(1, newPerPage)}
              variant="bottom"
              isCompact
            />
          </ToolbarItem>
        </ToolbarContent>
      </Toolbar>
    </>
  );
}

// ui/poc-lit/src/components/connectors-table.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { EnrichedConnector, ConnectorState, ConnectorType } from '../api/kafka-connect';
import { tableStyles, statusStyles } from '../styles/shared-styles';

@customElement('connectors-table')
export class ConnectorsTable extends LitElement {
  @property({ type: Array }) connectors: EnrichedConnector[] = [];
  @property({ type: Boolean }) loading = false;
  @property({ type: String }) sortBy = 'name';
  @property({ type: String }) sortDirection: 'asc' | 'desc' = 'asc';
  @property({ type: String }) kafkaId = '';

  static styles = [
    tableStyles,
    statusStyles,
    css`
      .managed-label {
        display: inline-block;
        margin-left: var(--pf-v5-global--spacer--sm);
        padding: var(--pf-v5-global--spacer--xs) var(--pf-v5-global--spacer--sm);
        background-color: var(--pf-v5-global--BackgroundColor--200);
        border-radius: var(--pf-v5-global--BorderRadius--sm);
        font-size: var(--pf-v5-global--FontSize--xs);
        color: var(--pf-v5-global--Color--200);
      }

      .state-icon {
        display: inline-flex;
        align-items: center;
        gap: var(--pf-v5-global--spacer--xs);
      }
    `
  ];

  private handleSort(column: string) {
    if (this.sortBy === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortBy = column;
      this.sortDirection = 'asc';
    }

    this.dispatchEvent(new CustomEvent('sort-change', {
      detail: { sortBy: this.sortBy, sortDirection: this.sortDirection },
      bubbles: true,
      composed: true,
    }));
  }

  private getStateIcon(state: ConnectorState) {
    switch (state) {
      case 'RUNNING':
        return html`<span class="state-icon status-success">✓ Running</span>`;
      case 'PAUSED':
        return html`<span class="state-icon">⏸ Paused</span>`;
      case 'STOPPED':
        return html`<span class="state-icon">⏹ Stopped</span>`;
      case 'FAILED':
        return html`<span class="state-icon status-danger">✗ Failed</span>`;
      case 'RESTARTING':
        return html`<span class="state-icon">↻ Restarting</span>`;
      case 'UNASSIGNED':
        return html`<span class="state-icon status-warning">⊙ Unassigned</span>`;
      default:
        return html`<span class="state-icon">${state}</span>`;
    }
  }

  private getTypeLabel(type: ConnectorType) {
    switch (type) {
      case 'source':
        return 'Source';
      case 'sink':
        return 'Sink';
      case 'source:mm':
        return 'Mirror Source';
      case 'source:mm-checkpoint':
        return 'Mirror Checkpoint';
      case 'source:mm-heartbeat':
        return 'Mirror Heartbeat';
      default:
        return type;
    }
  }

  private getSortIndicator(column: string) {
    if (this.sortBy !== column) return '';
    return this.sortDirection === 'asc' ? '↑' : '↓';
  }

  render() {
    if (this.loading) {
      return html`
        <div class="pf-v5-c-empty-state">
          <div class="pf-v5-c-empty-state__content">
            <div class="pf-v5-c-spinner pf-m-xl" role="progressbar">
              <span class="pf-v5-c-spinner__clipper"></span>
              <span class="pf-v5-c-spinner__lead-ball"></span>
              <span class="pf-v5-c-spinner__tail-ball"></span>
            </div>
            <div class="pf-v5-c-empty-state__body">Loading connectors...</div>
          </div>
        </div>
      `;
    }

    if (this.connectors.length === 0) {
      return html`
        <div class="pf-v5-c-empty-state">
          <div class="pf-v5-c-empty-state__content">
            <div class="pf-v5-c-empty-state__icon">
              <i class="fas fa-plug" aria-hidden="true"></i>
            </div>
            <h2 class="pf-v5-c-title pf-m-lg">No connectors found</h2>
            <div class="pf-v5-c-empty-state__body">
              There are no connectors in this Kafka cluster yet.
            </div>
          </div>
        </div>
      `;
    }

    return html`
      <table class="pf-v5-c-table pf-m-grid-md" role="grid">
        <thead>
          <tr role="row">
            <th role="columnheader" @click=${() => this.handleSort('name')}>
              Name
              <span class="sort-indicator">${this.getSortIndicator('name')}</span>
            </th>
            <th role="columnheader">Connect Cluster</th>
            <th role="columnheader">Type</th>
            <th role="columnheader" @click=${() => this.handleSort('state')}>
              State
              <span class="sort-indicator">${this.getSortIndicator('state')}</span>
            </th>
            <th role="columnheader">Tasks</th>
          </tr>
        </thead>
        <tbody role="rowgroup">
          ${this.connectors.map(connector => html`
            <tr role="row">
              <td role="cell" data-label="Name">
                <a href="/kafka/${this.kafkaId}/kafka-connect/${encodeURIComponent(connector.id)}">
                  ${connector.attributes.name}
                </a>
                ${connector.meta?.managed ? html`<span class="managed-label">Managed</span>` : ''}
              </td>
              <td role="cell" data-label="Connect Cluster">
                ${connector.connectClusterId ? html`
                  <a href="/kafka/${this.kafkaId}/kafka-connect/connect-clusters/${connector.connectClusterId}">
                    ${connector.connectClusterName}
                  </a>
                ` : '-'}
              </td>
              <td role="cell" data-label="Type">
                ${this.getTypeLabel(connector.attributes.type)}
              </td>
              <td role="cell" data-label="State">
                ${this.getStateIcon(connector.attributes.state)}
              </td>
              <td role="cell" data-label="Tasks">
                ${connector.replicas ?? '-'}
              </td>
            </tr>
          `)}
        </tbody>
      </table>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'connectors-table': ConnectorsTable;
  }
}

// Made with Bob
